### ISSUE TITLE
Snapchat API: 405 HTTP method GET is not supported by this URL

### ISSUE THREAD

**Issue by evanugarte** [cipriansofronia/snapchat-memories-downloader#1]
Running the application locally, I see that trying to request the `"Download Link"` field in `memories_history.json` results in a 405 response:

![image](https://user-images.githubusercontent.com/36345325/78586850-ed945880-77f0-11ea-9479-43cd32c446db.png)

I thought maybe trying a `POST` request instead would solve this, but instead I got this response:
![image](https://user-images.githubusercontent.com/36345325/78586918-0dc41780-77f1-11ea-9c98-ca542218a454.png)

Any ideas on this? Are these URLs not accessible anymore?

**Comment by cipriandrei10** [comment]
I'll check if something changed in snapchat's memories file since this tool was released, but be aware that each `Download Link` has a TTL on it, so maybe that expired.

**Comment by cipriansofronia** [comment]
Just checked and I get the same thing, so, something changed on their side because it appears that I don't have permission to access those files. I'll try to contact them.

**Comment by cipriandrei10** [comment]
Ok, so, it looks like things changed there apparently :roll_eyes: 
It's a 2 step process: 
1. split the `Download Link` by `?` and use the first part of it to send a `POST` request with `Content-type:application/x-www-form-urlencoded` header and as a body the 2nd part of the `Download Link` - the response contains another link
2. use the response link u got from step 1 and send a `GET` request with it and the media should download now

Obviously, doing this by hand for each media file is not an option, so, I'll update this tool to consider the latest changes. Thank you for pointing it out!

**Comment by evanugarte** [comment]
I made use of node's [fetch API](https://formcarry.com/documentation/fetch-api-example) to try and make an example request like below:
```js
fetch('https://app.snapchat.com/dmd/memories', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-url-encoded' },
  body: 'uid=<uid from json>&mid=<mid from json>&etc...'
})
  .then(res => {
    // print the entire http response
    console.debug(res);
    // print the server's http response code
    console.debug(res.statis);
  })
  .catch((err) => {
    console.debug(err);
  });
```

However I still got a 403 response: 
![image](https://user-images.githubusercontent.com/36345325/78625887-142eaf80-7842-11ea-9272-6330ba0cba71.png)

Would you know how long the TTL might be? I had downloaded the `.zip` file from snapchat about 12 hours ago. I also reached out to snapchat regarding the issue and will let you know what they say.

**Comment by cipriandrei10** [comment]
I was able to do this via Postman. I can see that the TTL is set to 7 days, check `X-Amz-Expires` from the response URL u received from `https://app.snapchat.com/dmd/memories`

**Comment by evanugarte** [comment]
It works! Thank you so much! This tool you have made is super awesome.

**Comment by evanugarte** [comment]
just for fun find my implementation below to gather all AWS links in js

```js
const axios = require('axios')
const fs = require('fs')
const memories = require('./memories_history')

function addJsonToFile(json) {
  fs.writeFile(__dirname + '/aws_links.json', JSON.stringify(json), err => {
    if (err) throw err
    else console.log('should be ok....');
  })
}

function recordError(link) {
  fs.appendFile(__dirname + '/errors.txt', `${link}\n`, _ => { })
}

async function main() {
  let snapchatMemoryData = []
  let completed = 0;
  await Promise.all(
    memories['Saved Media'].map(async (memory, index) => {
      await axios.post(memory['Download Link'])
        .then(res => {
          snapchatMemoryData.push({ date: memory['Date'], awsLink: res.data })
          completed++;
          console.log(`Completed ${completed} / ${memories['Saved Media'].length}...`);
        })
        .catch(_ => recordError(memory['Download Link']))
    })
  )
  addJsonToFile(snapchatMemoryData)
}

main()
```

**Comment by cipriandrei10** [comment]
Thank you! I'm glad that I helped someone else than my self :sweat_smile:
