### ISSUE TITLE
Parameter to choose how many memories to download?

### ISSUE THREAD

**Issue by ustincameron** [cipriansofronia/snapchat-memories-downloader#2]
Awesome project!

I have over 12,000 URLs in my memories.json, what's the best way to download the last 1,000 only or perhaps only memories after a certain date?

**Comment by cipriandrei10** [comment]
These features are not yet there, but I could make some time and add them. For now, unfortunately, you'll have to alter the json and take only last `n` elements from that json list. There should be some online tools that could help you in this way.

**Comment by cipriandrei10** [comment]
@ustincameron, there's a new release that adds these options for you.
Try it and let me know if you encounter any issues.
Thanks!
