### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by somjelly1** [cipriansofronia/snapchat-memories-downloader#4]
tried multiple times and am getting this error

C:\Users\damas\Downloads>java -jar s.jar -f C:\Users\damas\Desktop\New folder\json\memories_history.json
Error: Unknown argument 'folder\json\memories_history.json'
Try --help for more information.
07:38:34.757 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
07:38:34.764 [zio-default-async-11-14274612] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
07:38:34.764 [zio-default-async-11-14274612] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
07:38:34.767 [zio-default-async-11-14274612] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@611762
07:38:34.777 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
07:38:34.778 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
07:38:34.778 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
07:38:34.779 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
07:38:34.780 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
07:38:34.780 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
07:38:34.780 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
07:38:34.782 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
07:38:34.782 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
07:38:34.782 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
07:38:34.783 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
07:38:34.783 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\damas\AppData\Local\Temp (java.io.tmpdir)
07:38:34.783 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 32 (sun.arch.data.model)
07:38:34.784 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 259522560 bytes
07:38:34.784 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
07:38:34.785 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
07:38:34.785 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
07:38:34.790 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
07:38:35.278 [zio-default-async-11-14274612] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1]
07:38:35.278 [zio-default-async-11-14274612] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA]
07:38:35.290 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
07:38:35.291 [zio-default-async-11-14274612] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
07:38:35.294 [zio-default-async-11-14274612] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
07:38:35.299 [zio-default-async-11-14274612] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
07:38:35.300 [zio-default-async-11-14274612] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
07:38:35.324 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 2
07:38:35.324 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 2
07:38:35.324 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
07:38:35.324 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
07:38:35.324 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
07:38:35.324 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
07:38:35.325 [zio-default-async-11-14274612] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
07:38:35.330 [zio-default-async-11-14274612] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
07:38:35.330 [zio-default-async-11-14274612] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
07:38:35.330 [zio-default-async-11-14274612] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
07:38:35.384 [zio-default-async-11-14274612] ERROR io.snapchat.memories.Main$ - Program error! Message: Configuration error! Try --help for information!
io.snapchat.memories.models.ConfigError: Configuration error! Try --help for information!
        at io.snapchat.memories.modules.OptionParserOps$$anon$1.$anonfun$parse$4(OptionParserOps.scala:85)
        at zio.ZIO$.$anonfun$fail$1(ZIO.scala:2596)
        at zio.internal.FiberContext.evaluateNow(FiberContext.scala:406)
        at zio.internal.FiberContext.$anonfun$fork$11(FiberContext.scala:749)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by cipriandrei10** [comment]
Hi @somjelly1, try adding some quotes to the path.. something like that: 

`java -jar s.jar -f "C:\Users\damas\Desktop\New folder\json\memories_history.json"`

There is a space in `New folder` and the command parser thinks is a new option.. try the quotes or maybe try renaming `New folder` into something that doesn't have spaces in it.
